### ISSUE TITLE
Find a way for p.plot to handle dates on x axis

### ISSUE THREAD

**Issue by robdmc** [robdmc/pandashells#18]
Maybe as both datetimes and strings?

**Comment by kmatt** [comment]
p.plot seems to work with an x-axis containing dates in strings (YYYY-MM-DD), but p.regplot does not, even if the column is cast to a datetime?:

    p.df -i csv --names dt  count | p.df "df['dt'] = pd.to_datetime(df['dt'])" | p.regplot -x dt -y count

    Traceback (most recent call last):
      File "//anaconda/envs/py34/bin/p.regplot", line 9, in <module>
        load_entry_point('pandashells==0.1.4', 'console_scripts', 'p.regplot')()
      File "//anaconda/envs/py34/lib/python3.4/site-packages/pandashells/bin/p_regplot.py", line 108, in main
        coeffs = np.polyfit(x, y, args.order[0])
      File "//anaconda/envs/py34/lib/python3.4/site-packages/numpy/lib/polynomial.py", line 543, in polyfit
        x = NX.asarray(x) + 0.0
    TypeError: Can't convert 'float' object to str implicitly

**Comment by CarlQLange** [comment]
this would be huge. dates that aren't just a year or a day would be great to have.
